import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import LeftSidebar from '@/components/shared/LeftSidebar'
import Topbar from '@/components/shared/Topbar'
import Bottombar from '@/components/shared/Bottombar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
    <body>

      <Topbar />

      <main className='flex flex-row'>
        <LeftSidebar />
        <section className='flex flex-1 flex-col pb-5 mt-[55px] max-md:pb-32 sm:px-10 h-[0%] overflow-auto border'>
          <div className='w-full max-w-4xl'>{children}</div>
        </section>
        {/* @ts-ignore */}
      </main>

      <Bottombar />
    </body>
  </html>
  )
}
