import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import LeftSidebar from '@/components/shared/LeftSidebar'
import Topbar from '@/components/shared/Topbar'
import Bottombar from '@/components/shared/Bottombar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
    <body>

          <div className='fixed top-0 z-30 flex w-full h-[40px] items-center justify-between border px-6 py-3'>
            <Topbar />
          </div>





      <main className='flex flex-row'>
        <LeftSidebar />
        <section className='flex flex-1 flex-col pb-5 max-md:pb-32 mt-[42px] ml-[13%] sm:px-10 h-[80%] overflow-auto border'>
          <div className='w-full'>{children}</div>
        </section>
        {/* @ts-ignore */}
      </main>

      <Bottombar />
    </body>
  </html>
  )
}
